version: '3.9'

services:
  ipfs:
    image: ipfs/kubo:v0.38.2
    container_name: ipfs_node
    restart: unless-stopped

    environment:
      IPFS_PROFILE: server

    volumes:
      - ./ipfs_staging:/export
      - ./ipfs_data:/data/ipfs

    ports:
      - "4101:4001"            # P2P TCP (changed)
      - "4101:4001/udp"        # P2P UDP (changed)
      - "127.0.0.1:5101:5001"  # API (changed)
      - "127.0.0.1:8101:8080"  # Gateway (changed)
